### ISSUE TITLE
esm package exports re-exporting cjs

### ISSUE THREAD

**Issue by dnalborczyk** [es-shims/Object.hasOwn#3]
@ljharb  thank you for maintaining the vast variety of ecma script api modules. this is much appreciated.

out of curiosity, what is the reasoning to provide package exports for `esm` while only re-exporting `cjs`. node.js would still need to run the code for `esm` imports as well as for `cjs` requires and bundlers would need to do pretty much the same. I'm failing to see any advantages. from my point of view it only looks like more boilerplate with no benefit. (please don't take it the wrong way.)

if a `full esm` export would be provided one could argue that node and a bundler would need a _much_ simpler and smaller api surface to load modules, and eventually, in the _very_ long run, `cjs` could potentially (and hopefully) be faced out.

**Comment by ljharb** [comment]
"full ESM" support provides no advantages as a bundler is always required, and CJS will literally *never* be phased out, it will be around forever.

The purpose of the ESM entry point is to provide named exports that support tree-shaking, and that's it. You're right that I could just omit it, and most of my packages don't bother to add it, precisely because native ESM offers basically zero value.
